name: Python Application CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 # Updated to v4

    - name: Set up Python
      uses: actions/setup-python@v5 # Updated to v5
      with:
        python-version: '3.9' # Match project's Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 # For linting

    - name: Lint with Flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        echo "Running Flake8 with strict checks (E9, F63, F7, F82)..."
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings for the main linting pass.
        # The GitHub editor is 127 chars wide
        echo "Running Flake8 with standard checks (exit-zero)..."
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # Placeholder for tests
    # - name: Test with pytest
    #   run: |
    #     pip install pytest
    #     pytest 